export const FETCH_UNWATCHED_ACCOUNTS = 'FETCH_UNWATCHED_ACCOUNTS';
export const SUCCESS_FETCH_UNWATCHED_ACCOUNTS = 'SUCCESS_FETCH_UNWATCHED_ACCOUNTS';
export const ERROR_FETCH_UNWATCHED_ACCOUNTS = 'ERROR_FETCH_UNWATCHED_ACCOUNTS';

export const FETCH_ACCOUNT_DATA = 'FETCH_ACCOUNT_DATA';
export const SUCCESS_FETCH_ACCOUNT_DATA = 'SUCCESS_FETCH_ACCOUNT_DATA';
export const ERROR_FETCH_ACCOUNT_DATA = 'SUCCESS_FETCH_ACCOUNT_DATA';

export const FETCH_ADD_FREE_BET_FOR_ACCOUNT = 'FETCH_ADD_FREE_BET_FOR_ACCOUNT';
export const ADD_FREE_BET_FOR_ACCOUNT = 'ADD_FREE_BET_FOR_ACCOUNT';
export const ERROR_ADD_FREE_BET_FOR_ACCOUNT = 'ERROR_ADD_FREE_BET_FOR_ACCOUNT';

export const FETCH_FREE_BETS_INFO = 'FETCH_FREE_BETS_INFO';
export const SUCCESS_FETCH_FREE_BETS_INFO = 'SUCCESS_FETCH_FREE_BETS_INFO';
export const ERROR_FETCH_FREE_BETS_INFO = 'ERROR_FETCH_FREE_BETS_INFO';

export const RESET_STATE_DATA_ACCOUNT = 'RESET_STATE_DATA_ACCOUNT';

export const SUCCESS_FETCH_ACCOUNTS_STATS = 'FETCH_ACCOUNTS_STATS';
export const ERROR_FETCH_ACCOUNTS_STATS = 'FETCH_ACCOUNTS_STATS';

export const FETCH_WATCHED_ACCOUNTS = 'FETCH_WATCHED_ACCOUNTS';
export const SUCCESS_FETCH_WATCHED_ACCOUNTS = 'SUCCESS_FETCH_WATCHED_ACCOUNTS';
export const ERROR_FETCH_WATCHED_ACCOUNTS = 'ERROR_FETCH_WATCHED_ACCOUNTS';